import "./globals.css";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import Header from "@/components/header/header";
import Providers from "@/components/providers";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PetStay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={josefinSans.className}>
        <Providers>
          <Header />
          <main className="container py-8">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
